name: coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10, 3.11, 3.12]
        # exclude:
        #   - os: macos-latest
        #     python-version: 3.8
        #   - os: windows-latest
        #     python-version: 3.6
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Tests with Nox

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: x64
    - run: pip install nox
    - run: pip install poetry
    - run: nox --sessions tests coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}


